### PR TITLE
Fixes #107

### LINKED ISSUE #107: Class App\Http\Controllers\Auth\RegisterController does not exist
Few PHP artisan commands fail saying "Class App\Http\Controllers\Auth\RegisterController does not exist".
The path has no file as RegisterController.php

### PR DESCRIPTION
**Pull request by jhuebel**
This fixes issue #107.

### CODE REVIEW

File: routes/web.php [hunk 1]
```diff
@@ -9,17 +9,30 @@
 | to using a Closure or controller method. Build something great!
 |
 */
-Route::auth();
-Route::get('/logout', 'Auth\LoginController@logout');
+
+// Login/Logout Routes
+Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
+Route::post('login', 'Auth\LoginController@login');
+Route::get('logout', 'Auth\LoginController@logout')->name('logout');
```
Comment (Bottelet) [inline routes/web.php]: This should at some point be made into a post request :)

**Comment by Bottelet** [comment]
Awesome Thanks for the PR!
